### ISSUE TITLE
Don't working. script

### ISSUE THREAD

**Issue by Cryosim** [avislab/weather#1]
python /home/pi/weather/weather.py
Temperature: 22.3 °C Pressure: 460.25 mm Hg Humidity: 89.41 %
Traceback (most recent call last):
  File "/home/pi/weather/weather.py", line 124, in <module>
    response = urllib2.urlopen("http://avispro.com.ua/getdata.php?data="+s)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by avislab** [comment]
Really?

Let's see what's wrong on line 124 in weather.py !!!

response = urllib2.urlopen ("http://avispro.com.ua/getdata.php?data=" + s)

Oops http://avispro.com.ua ??? Is this your site? Not? Please enter the path to the script on your site in line 124 in the weather.py file.
